services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cognitive-ats-postgres
    environment:
      POSTGRES_DB: cognitive_ats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cognitive-ats-network
    restart: unless-stopped

  # Backend NestJS - Companies Service
  companies-backend:
    build:
      context: ./companies-service/backend
      dockerfile: Dockerfile.dev
    container_name: cognitive-ats-companies-backend-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=cognitive_ats
      - DB_DATABASE=cognitive_ats
      - AI_SERVICE_URL=http://ai-service:8000
      - ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - RESUMES_BUCKET_NAME=cognitive-ats-uploads
      - APPLICATIONS_SQS_QUEUE_NAME=applications-queue
    volumes:
      - ./companies-service/backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - ai-service
      - localstack
    networks:
      - cognitive-ats-network
    restart: unless-stopped

  # Frontend React - Companies Service (Desenvolvimento)
  companies-frontend:
    build:
      context: ./companies-service/frontend
      dockerfile: Dockerfile.dev
    container_name: cognitive-ats-companies-frontend-dev
    ports:
      - "8080:5173"
    volumes:
      - ./companies-service/frontend:/app
      - /app/node_modules
    depends_on:
      - companies-backend
    networks:
      - cognitive-ats-network
    restart: unless-stopped

  # AI Service (FastAPI)
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: cognitive-ats-ai-service
    ports:
      - "8000:8000"
    environment:
      - DEFAULT_AI_PROVIDER=openai
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    volumes:
      - ./ai-service:/app
    networks:
      - cognitive-ats-network
    restart: unless-stopped
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

  # LocalStack (AWS Services Simulator)
  localstack:
    image: localstack/localstack:latest
    container_name: cognitive-ats-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cognitive-ats-network
    restart: unless-stopped



volumes:
  postgres_data:

networks:
  cognitive-ats-network:
    driver: bridge 