# syntax=docker/dockerfile:1

FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
	PYTHONUNBUFFERED=1

WORKDIR /app

# Dependências do sistema mínimas
RUN apt-get update -y && apt-get install -y --no-install-recommends \
	ca-certificates \
	&& rm -rf /var/lib/apt/lists/*

# Instalar dependências Python (inclui deps de dev)
COPY requirements.txt requirements.txt
COPY requirements-dev.txt requirements-dev.txt
RUN pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt

# Copiar código (compose montará volume em dev)
COPY src /app/src

# Comando padrão para dev
CMD ["python", "src/consumer.py"]


